on: push
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - uses: node --version
      - uses: npm --version
      - uses: actions/checkout@v4
      - uses: npm install
      - uses: node app.js
        with:
          node-version: 20
      - run: npm ci
      - run: npm test



#  publish-gpr:
#    needs: build
#    runs-on: ubuntu-latest
#    permissions:
#      contents: read
#      packages: write
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-node@v4
#        with:
#          node-version: 20
#          registry-url: https://marcelojsil.github.com/marthec
#      - run: npm ci
#      - run: npm publish
#        env:
#          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
